#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug/
/sbin/mdev -s
echo "---------------------------------------------"
echo "-----------------Booting Linux --------------"
echo "---------------------------------------------"
